name: ImpEx
run-name: CI/CD Demo

on:
  workflow_dispatch:

jobs:
  export:
    environment: SIT
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install Node Dependencies
        run: npm ci

      - name: Execute Export API Request
        run: |
          node -e 'require("./script.js").exp("${{ vars.CS_URL_REGION }}","${{ vars.CS_TENANT_NAME }}","${{ vars.CS_BEARER_TOKEN }}","${{ vars.CS_SERVICE_URI_SOURCE }}")'
          [ -f package.zip ] && du -sh package.zip

      - name: Persist exported entities as artifact
        uses: actions/upload-artifact@v3
        with:
          name: exported
          path: package.zip
          retention-days: 1

  import:
    environment: UAT
    runs-on: ubuntu-latest
    needs: export
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install Node Dependencies
        run: npm ci

      - name: Download exported entities from artifact
        uses: actions/download-artifact@v3
        with:
          name: exported
      - name: Execute Import API Request
        run: |
          node -e 'require("./script.js").imp("${{ vars.CS_URL_REGION }}","${{ vars.CS_TENANT_NAME }}","${{ vars.CS_BEARER_TOKEN }}","${{ vars.CS_SERVICE_URI_SOURCE }}", "${{ vars.CS_SERVICE_URI_TARGET }}")'
          rm -f package.zip
